/**
 * Fetching hard coded jobs at random for now.
 * Later solve for many jobs - probably using Redis
 */
const tmpHardCodedJobs = [
  {
    country: "New Zealand",
    radius: "100",
    radius_unit: "kilometres",
    days_listed: 1,
    exact: true,
    top_results: 5,
    not_include: "case",
    city: "Christchurch",
    product: "iPhone 11",
    min_price: 30,
    max_price: 395,
  },
  {
    country: "New Zealand",
    radius: "100",
    radius_unit: "kilometres",
    days_listed: 1,
    exact: true,
    top_results: 5,
    not_include: "case",
    city: "Christchurch",
    product: "iPhone 12",
    min_price: 50,
    max_price: 545,
  },
  {
    country: "New Zealand",
    radius: "100",
    radius_unit: "kilometres",
    days_listed: 1,
    exact: true,
    top_results: 5,
    not_include: "case",
    city: "Christchurch",
    product: "iPhone 13",
    min_price: 50,
    max_price: 700,
  },
  {
    country: "New Zealand",
    radius: "100",
    radius_unit: "kilometres",
    days_listed: 1,
    exact: true,
    top_results: 5,
    not_include: "case",
    city: "Christchurch",
    product: "iPhone 14",
    min_price: 50,
    max_price: 900,
  },
  {
    country: "New Zealand",
    radius: "100",
    radius_unit: "kilometres",
    days_listed: 1,
    exact: true,
    top_results: 5,
    not_include: "case",
    city: "Christchurch",
    product: "iPhone 15",
    min_price: 50,
    max_price: 900,
  },
  {
    country: "New Zealand",
    radius: "100",
    radius_unit: "kilometres",
    days_listed: 1,
    exact: true,
    top_results: 5,
    not_include: "case",
    city: "Christchurch",
    product: "iPhone 15",
    min_price: 100,
    max_price: 1400,
  },
  {
    country: "New Zealand",
    radius: "100",
    radius_unit: "kilometres",
    days_listed: 1,
    exact: true,
    top_results: 5,
    not_include: "case",
    city: "Christchurch",
    product: "iPhone 16",
    min_price: 100,
    max_price: 1750,
  },
  {
    country: "New Zealand",
    radius: "100",
    radius_unit: "kilometres",
    days_listed: 1,
    exact: true,
    top_results: 5,
    not_include: "case",
    city: "Wellington",
    product: "iPhone 11",
    min_price: 30,
    max_price: 395,
  },
  {
    country: "New Zealand",
    radius: "100",
    radius_unit: "kilometres",
    days_listed: 1,
    exact: true,
    top_results: 5,
    not_include: "case",
    city: "Wellington",
    product: "iPhone 12",
    min_price: 50,
    max_price: 545,
  },
  {
    country: "New Zealand",
    radius: "100",
    radius_unit: "kilometres",
    days_listed: 1,
    exact: true,
    top_results: 5,
    not_include: "case",
    city: "Wellington",
    product: "iPhone 13",
    min_price: 50,
    max_price: 700,
  },
  {
    country: "New Zealand",
    radius: "100",
    radius_unit: "kilometres",
    days_listed: 1,
    exact: true,
    top_results: 5,
    not_include: "case",
    city: "Wellington",
    product: "iPhone 14",
    min_price: 50,
    max_price: 900,
  },
  {
    country: "New Zealand",
    radius: "100",
    radius_unit: "kilometres",
    days_listed: 1,
    exact: true,
    top_results: 5,
    not_include: "case",
    city: "Wellington",
    product: "iPhone 15",
    min_price: 50,
    max_price: 900,
  },
  {
    country: "New Zealand",
    radius: "100",
    radius_unit: "kilometres",
    days_listed: 1,
    exact: true,
    top_results: 5,
    not_include: "case",
    city: "Wellington",
    product: "iPhone 15",
    min_price: 100,
    max_price: 1400,
  },
  {
    country: "New Zealand",
    radius: "100",
    radius_unit: "kilometres",
    days_listed: 1,
    exact: true,
    top_results: 5,
    not_include: "case",
    city: "Wellington",
    product: "iPhone 16",
    min_price: 100,
    max_price: 1750,
  },
  {
    country: "New Zealand",
    radius: "100",
    radius_unit: "kilometres",
    days_listed: 1,
    exact: true,
    top_results: 5,
    not_include: "case",
    city: "Auckland",
    product: "iPhone 11",
    min_price: 30,
    max_price: 395,
  },
  {
    country: "New Zealand",
    radius: "100",
    radius_unit: "kilometres",
    days_listed: 1,
    exact: true,
    top_results: 5,
    not_include: "case",
    city: "Auckland",
    product: "iPhone 12",
    min_price: 50,
    max_price: 545,
  },
  {
    country: "New Zealand",
    radius: "100",
    radius_unit: "kilometres",
    days_listed: 1,
    exact: true,
    top_results: 5,
    not_include: "case",
    city: "Auckland",
    product: "iPhone 13",
    min_price: 50,
    max_price: 700,
  },
  {
    country: "New Zealand",
    radius: "100",
    radius_unit: "kilometres",
    days_listed: 1,
    exact: true,
    top_results: 5,
    not_include: "case",
    city: "Auckland",
    product: "iPhone 14",
    min_price: 50,
    max_price: 900,
  },
  {
    country: "New Zealand",
    radius: "100",
    radius_unit: "kilometres",
    days_listed: 1,
    exact: true,
    top_results: 5,
    not_include: "case",
    city: "Auckland",
    product: "iPhone 15",
    min_price: 50,
    max_price: 900,
  },
  {
    country: "New Zealand",
    radius: "100",
    radius_unit: "kilometres",
    days_listed: 1,
    exact: true,
    top_results: 5,
    not_include: "case",
    city: "Auckland",
    product: "iPhone 15",
    min_price: 100,
    max_price: 1400,
  },
  {
    country: "New Zealand",
    radius: "100",
    radius_unit: "kilometres",
    days_listed: 1,
    exact: true,
    top_results: 5,
    not_include: "case",
    city: "Auckland",
    product: "iPhone 16",
    min_price: 100,
    max_price: 1750,
  },
];

export async function next() {
  await new Promise((res) => setTimeout(res, 2)); // simulate some DB/Redis/Kafka wait time
  return tmpHardCodedJobs[Math.floor(Math.random() * tmpHardCodedJobs.length)];
}
